# Packages

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/A0008D - v_pt_ride_all (full).csv')

In [3]:
df['BIZ_DT'] = pd.to_datetime(df['BIZ_DT'])
df['ENTRY_DT'] = pd.to_datetime(df['ENTRY_DT'])
df['EXIT_DT'] = pd.to_datetime(df['EXIT_DT'])
#df['ENTRY_TM'] = pd.to_datetime(df['ENTRY_TM'], format='%H:%M:%S.%f')
#df['EXIT_TM'] = pd.to_datetime(df['EXIT_TM'], format='%H:%M:%S.%f')

In [4]:
df1 = df[df['ENTRY_DT'] == '2025-02-11'].copy()
df1.columns
df2 = df1[['BUS_SVC_NUM', 'CRD_NUM', 'DEST_LOC_ID_NUM', 'ENTRY_DT',
       'ENTRY_TM', 'EXIT_DT', 'EXIT_TM', 'ORIG_LOC_ID_NUM', 'RIDE_DISC_AMT', 'RIDE_DIST_KM_CNT',
       'RIDE_FARE_AMT', 'RIDE_ID_NUM', 'RIDE_MIN_CNT']].reset_index()
df2.head()

,index,BUS_SVC_NUM,CRD_NUM,DEST_LOC_ID_NUM,ENTRY_DT,ENTRY_TM,EXIT_DT,EXIT_TM,ORIG_LOC_ID_NUM,RIDE_DISC_AMT,RIDE_DIST_KM_CNT,RIDE_FARE_AMT,RIDE_ID_NUM,RIDE_MIN_CNT
0,58167,62.0,200003194601,6492,2025-02-11,00:47:26.000,2025-02-11,01:13:17.000,3979,0.0,9.1,1.73,110848327669,25.850
1,59621,117.0,230021568683,6034,2025-02-11,00:23:54.000,2025-02-11,00:29:20.000,6042,0.0,1.1,1.19,110848360426,5.433
2,60686,NaN,230036729632,325,2025-02-11,00:03:46.000,2025-02-11,00:18:29.000,320,0.0,6.1,1.50,110848362684,14.717
3,61474,235.0,2190006112681,3380,2025-02-11,00:33:00.000,2025-02-11,00:36:29.000,6984,0.0,0.8,0.00,110848329634,3.483
4,61528,979.0,190002646194,2997,2025-02-11,00:01:31.000,2025-02-11,00:29:25.000,6901,0.0,6.7,0.24,110848330026,27.900

In [5]:
bus_data = pd.read_csv('../data/A0008D - v_q_bus_stop (full).csv')

In [6]:
df2 = df2.merge(bus_data, how = 'left', left_on= 'DEST_LOC_ID_NUM',
                right_on= 'MRK_ID_NUM')
df2.head(5)

,index,BUS_SVC_NUM,CRD_NUM,DEST_LOC_ID_NUM,ENTRY_DT,ENTRY_TM,EXIT_DT,EXIT_TM,ORIG_LOC_ID_NUM,RIDE_DISC_AMT,RIDE_DIST_KM_CNT,RIDE_FARE_AMT,RIDE_ID_NUM,RIDE_MIN_CNT,BUS_STOP_CD,BUS_STOP_NAM,MRK_ID_NUM,RD_NAM
0,58167,62.0,200003194601,6492,2025-02-11,00:47:26.000,2025-02-11,01:13:17.000,3979,0.0,9.1,1.73,110848327669,25.850,65179.0,Coral Edge Stn Exit A,6492.0,Punggol Field
1,59621,117.0,230021568683,6034,2025-02-11,00:23:54.000,2025-02-11,00:29:20.000,6042,0.0,1.1,1.19,110848360426,5.433,58519.0,Opp Blk 104B,6034.0,CANBERRA ST
2,60686,NaN,230036729632,325,2025-02-11,00:03:46.000,2025-02-11,00:18:29.000,320,0.0,6.1,1.50,110848362684,14.717,NaN,NaN,NaN,NaN
3,61474,235.0,2190006112681,3380,2025-02-11,00:33:00.000,2025-02-11,00:36:29.000,6984,0.0,0.8,0.00,110848329634,3.483,52161.0,Braddell Stn/Blk 111,3380.0,LOR 1 TOA PAYOH
4,61528,979.0,190002646194,2997,2025-02-11,00:01:31.000,2025-02-11,00:29:25.000,6901,0.0,6.7,0.24,110848330026,27.900,45399.0,Regent Gr Condo,2997.0,CHOA CHU KANG NORTH 7

In [7]:
df2 = df2.rename(columns={
    'BUS_STOP_CD': 'DEST_BUS_STOP_CD',
    'BUS_STOP_NAM': 'DEST_BUS_STOP_NAM',
    'MRK_ID_NUM': 'DEST_MRK_ID_NUM',
    'RD_NAM': 'DEST_RD_NAM',
})

In [8]:
df2 = df2.merge(bus_data, how = 'left', left_on= 'ORIG_LOC_ID_NUM',
                right_on= 'MRK_ID_NUM')

In [9]:
df2 = df2.rename(columns={
    'BUS_STOP_CD': 'ORIG_BUS_STOP_CD',
    'BUS_STOP_NAM': 'ORIG_BUS_STOP_NAM',
    'MRK_ID_NUM': 'ORIG_MRK_ID_NUM',
    'RD_NAM': 'ORIG_RD_NAM',
})
df2.head(5)

,index,BUS_SVC_NUM,CRD_NUM,DEST_LOC_ID_NUM,ENTRY_DT,ENTRY_TM,EXIT_DT,EXIT_TM,ORIG_LOC_ID_NUM,RIDE_DISC_AMT,...,RIDE_ID_NUM,RIDE_MIN_CNT,DEST_BUS_STOP_CD,DEST_BUS_STOP_NAM,DEST_MRK_ID_NUM,DEST_RD_NAM,ORIG_BUS_STOP_CD,ORIG_BUS_STOP_NAM,ORIG_MRK_ID_NUM,ORIG_RD_NAM
0,58167,62.0,200003194601,6492,2025-02-11,00:47:26.000,2025-02-11,01:13:17.000,3979,0.0,...,110848327669,25.850,65179.0,Coral Edge Stn Exit A,6492.0,Punggol Field,62229.0,The Minton,3979.0,Lor Ah Soo
1,59621,117.0,230021568683,6034,2025-02-11,00:23:54.000,2025-02-11,00:29:20.000,6042,0.0,...,110848360426,5.433,58519.0,Opp Blk 104B,6034.0,CANBERRA ST,58549.0,Canberra Stn,6042.0,CANBERRA LK
2,60686,NaN,230036729632,325,2025-02-11,00:03:46.000,2025-02-11,00:18:29.000,320,0.0,...,110848362684,14.717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,61474,235.0,2190006112681,3380,2025-02-11,00:33:00.000,2025-02-11,00:36:29.000,6984,0.0,...,110848329634,3.483,52161.0,Braddell Stn/Blk 111,3380.0,LOR 1 TOA PAYOH,52559.0,Caldecott Stn Exit 1,6984.0,TOA PAYOH LK
4,61528,979.0,190002646194,2997,2025-02-11,00:01:31.000,2025-02-11,00:29:25.000,6901,0.0,...,110848330026,27.900,45399.0,Regent Gr Condo,2997.0,CHOA CHU KANG NORTH 7,45009.0,Bukit Panjang Interchange B3,6901.0,JELEBU RD

In [10]:
bus_vls_data = pd.read_csv('../data/A0008D - v_q_vls_marker (full).csv')

In [11]:
df3 = df2.merge(bus_vls_data, how = 'left', left_on= 'DEST_MRK_ID_NUM',
                right_on= 'MRK_ID_NUM')
df3 = df3.rename(columns={
    'LATITUDE_VAL': 'DEST_LATITUDE_VAL',
    'LONGITUDE_VAL': 'DEST_LONGITUDE_VAL',
})
df3.head(3)

,index,BUS_SVC_NUM,CRD_NUM,DEST_LOC_ID_NUM,ENTRY_DT,ENTRY_TM,EXIT_DT,EXIT_TM,ORIG_LOC_ID_NUM,RIDE_DISC_AMT,...,DEST_BUS_STOP_NAM,DEST_MRK_ID_NUM,DEST_RD_NAM,ORIG_BUS_STOP_CD,ORIG_BUS_STOP_NAM,ORIG_MRK_ID_NUM,ORIG_RD_NAM,MRK_ID_NUM,DEST_LATITUDE_VAL,DEST_LONGITUDE_VAL
0,58167,62.0,200003194601,6492,2025-02-11,00:47:26.000,2025-02-11,01:13:17.000,3979,0.0,...,Coral Edge Stn Exit A,6492.0,Punggol Field,62229.0,The Minton,3979.0,Lor Ah Soo,6492.0,5019504.0,374083039.0
1,59621,117.0,230021568683,6034,2025-02-11,00:23:54.000,2025-02-11,00:29:20.000,6042,0.0,...,Opp Blk 104B,6034.0,CANBERRA ST,58549.0,Canberra Stn,6042.0,CANBERRA LK,6034.0,5212670.0,373789443.0
2,60686,NaN,230036729632,325,2025-02-11,00:03:46.000,2025-02-11,00:18:29.000,320,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df3 = df3.merge(bus_vls_data, how = 'left', left_on= 'ORIG_MRK_ID_NUM',
                right_on= 'MRK_ID_NUM')
df3 = df3.rename(columns={
    'LATITUDE_VAL': 'ORIG_LATITUDE_VAL',
    'LONGITUDE_VAL': 'ORIG_LONGITUDE_VAL',
})
df3.head(5)

,index,BUS_SVC_NUM,CRD_NUM,DEST_LOC_ID_NUM,ENTRY_DT,ENTRY_TM,EXIT_DT,EXIT_TM,ORIG_LOC_ID_NUM,RIDE_DISC_AMT,...,ORIG_BUS_STOP_CD,ORIG_BUS_STOP_NAM,ORIG_MRK_ID_NUM,ORIG_RD_NAM,MRK_ID_NUM_x,DEST_LATITUDE_VAL,DEST_LONGITUDE_VAL,MRK_ID_NUM_y,ORIG_LATITUDE_VAL,ORIG_LONGITUDE_VAL
0,58167,62.0,200003194601,6492,2025-02-11,00:47:26.000,2025-02-11,01:13:17.000,3979,0.0,...,62229.0,The Minton,3979.0,Lor Ah Soo,6492.0,5019504.0,374083039.0,3979.0,4863864.0,373975849.0
1,59621,117.0,230021568683,6034,2025-02-11,00:23:54.000,2025-02-11,00:29:20.000,6042,0.0,...,58549.0,Canberra Stn,6042.0,CANBERRA LK,6034.0,5212670.0,373789443.0,6042.0,5193281.0,373788511.0
2,60686,NaN,230036729632,325,2025-02-11,00:03:46.000,2025-02-11,00:18:29.000,320,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,61474,235.0,2190006112681,3380,2025-02-11,00:33:00.000,2025-02-11,00:36:29.000,6984,0.0,...,52559.0,Caldecott Stn Exit 1,6984.0,TOA PAYOH LK,3380.0,4827108.0,373843642.0,6984.0,4811407.0,373822679.0
4,61528,979.0,190002646194,2997,2025-02-11,00:01:31.000,2025-02-11,00:29:25.000,6901,0.0,...,45009.0,Bukit Panjang Interchange B3,6901.0,JELEBU RD,2997.0,5039427.0,373499686.0,6901.0,4963266.0,373546001.0